openapi: 3.0.1
info:
  title: Eurostone.Webshop.API
  description: Harmadik fél számára nyújt elérhetőséget a Eurostone rendszerhez.
  contact:
    email: helpdesk@eurostone.hu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 24.1.2
# servers:
# - url: https://swseurostone.github.io/Eurostone.Webshop.Api.Document/
#   description: Api dokumentáció
tags:
- name: Partner
  description: Partner műveletek
- name: Lista Panel
  description: Lista panel műveletek

#Végpontok  
paths:
  /api/v1/partner/partnerInsert:
    post:
      tags:
        - Partner
      description: Partner felvétele a Partner törzsbe
      requestBody:
        description: Partner törzs egy tétele
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartnerInsertRequest'
      responses:
        "200":
          description: Partner létrehozás sikeres.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResponse'
        "400": 
          description: Partner létrehozás sikertelen.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResponse'
        "401": 
          description: Partner létrehozás sikertelen.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResponse'
        "422":
          description: Partner létrehozás sikertelen.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/OperationResponse'
  /api/v1/eslist/query:
    get:
      tags:
        - Lista Panel
      description: Listapanel adat lekérés. Lehet mező szűréssel, vagy szűrés nélkül. A "Filter" mező TÖMBként viselkedik, több mezőre is lehet egyszerre szűrni, ÉS kapcsolat lesz közöttük.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListPanelQueryRequest'
            examples:
              Szűrés nélkül:
                value:
                  ListPanelId: 1,
                  Filter: null
              Szűréssel:
                value:
                  ListPanelId: 1,
                  Filter: 
                    FieldName: Partner_Id,
                    FilterValue: 1-1
              Dátum szűréssel (intervallum):
                value:
                  ListPanelId: 5,
                  Filter:
                    FieldName: Date_Execution,
                    IntervalBegin: 2023-12-01,
                    IntervalEnd: 2023-12-31
      responses:
        "200":
          description: Lekérdezés sikeres
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResponse'
              example:
                  responseCode: null,
                  message: null,
                  messageEN: null,
                  details: null,
                  content: {
                      Data: [{
                            Partner_Id: 1-1,
                            Partner_Name: A nevem,
                            Partner_Code: 25,
                            .
                            .
                            .
                          },
                          {
                            Partner_Id: 1-2,
                            Partner_Name: Másik vagyok,
                            Partner_Code: 26,
                            .
                            .
                            .
                          }]
                  }
                  statusCode: 200
        "400": 
          description: Kérés sikertelen.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResponse'
              example:
                responseCode: Hibakód,
                details: A hibakódhozhoz tartozó üzenet,
                statusCode: 400
        "401": 
          description: Kérés sikertelen.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResponse'
              example:
                responseCode: Hibakód,
                details: A hibakódhozhoz tartozó üzenet,
                statusCode: 401
        "422":
          description: Kérés sikertelen.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/OperationResponse'
              example:
                responseCode: Hibakód,
                details: A hibakódhozhoz tartozó üzenet,
                statusCode: 422
  /api/v1/eslist/{panelId}/fields:
    get:
      tags:
          - Lista Panel
      description: Adott lista panel mezőinek lekérése
      parameters:
        - name: panelId
          in: path
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: Kérés sikeres.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResponse'
              example: 
                  responseCode: null,
                  message: null,
                  messageEN: null,
                  details: null,
                  content: {
                      Fields: [
                          Partner_Id,
                          Partner_Name,
                          Partner_Code,
                          .
                          .
                          .
                      ]
                  }
                  statusCode: 200
        "400": 
          description: Kérés sikertelen.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResponse'
              example:
                responseCode: Hibakód,
                details: A hibakódhozhoz tartozó üzenet,
                statusCode: 400
        "401": 
          description: Kérés sikertelen.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResponse'
              example:
                responseCode: Hibakód,
                details: A hibakódhozhoz tartozó üzenet,
                statusCode: 401
        "422":
          description: Kérés sikertelen.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/OperationResponse'
              example:
                responseCode: Hibakód,
                details: A hibakódhozhoz tartozó üzenet,
                statusCode: 422
# Objektumok
components:
  schemas:
    PartnerInsertRequest:
      required:
      - InvoiceCity
      - InvoiceCountry
      - InvoiceStreet
      - InvoiceZip
      - PartnerName
      - PartnerPaytypeId
      - PrivatePerson
      type: object
      properties:
        PartnerName:
          type: string
          description: "Partner neve, ami a számlára kerül"
          example: Teszt partner
        PartnerShortname:
          type: string
          description: "Partner neve rövidítve, ha nincs megadva akkor megegyezik a PartnerName mezővel"
          example: TPT
        PartnerPaytypeId:
          type: string
          description: Partner alapértelmezett fizetési módja
          example: 1-2
        PrivatePerson:
          type: boolean
          description: A partner magánszemély
          example: true
        TaxNumber:
          type: string
          description: "Adószám, megadása kötelező, ha a partner nem magánszemély"
          example: 12345678-9-10
        ContoNumber:
          type: string
          description: Partner bankszámlaszáma
        InvoiceCountryId:
          type: string
          description: Számlázási cím országkódja
          example: HU
        InvoiceZip:
          type: string
          description: Számlázási cím irányítószám
        InvoiceCity:
          type: string
          description: Számlázási cím helység
        InvoiceStreet:
          type: string
          description: Számlázási cím közterület
        InvoiceNumber:
          type: string
          description: Számlázási cím házszám
        Phone:
          type: string
          description: Partner telefonszáma
        Email:
          type: string
          description: Partner email címe
        SiteCountryId:
          type: string
          description: Telephely cím országkódja
          example: HU
        SiteZip:
          type: string
          description: Telephely cím irányítószáma
        SiteCity:
          type: string
          description: Telephely cím helység
        SiteStreet:
          type: string
          description: Telephely cím közterület
        SiteNumber:
          type: string
          description: Telephely cím házszáma
        SitePhone:
          type: string
          description: Telephely telefonszáma
        SiteEmail:
          type: string
          description: Telephely email címe
      description: Partner létrehozásához modell.
    # ListPanelSuccessResponse:
    #   type: object
    #   properties:
    #     Data:
    #       type: string
    #   description: Listapanel sikeres visszatérés
    ListPanelQueryRequest:
      required:
      - ListPanelId
      type: object
      properties:
        ListPanelId:
          type: integer
          description: Listapanel azonosítója
          format: int32
        Filter:
          type: array
          items:
            $ref: '#/components/schemas/ListPanelFilter'
      description: Listapanel lekérdezés törzse
    ListPanelFilter:
      type: object
      properties:
        FieldName:
          type: string
          description: Mező, amit szűr.
        FilterValue:
          type: object
          description: Érték, amire szűr.
        IntervalBegin:
          type: object
          description: Dátum szűrés kezdő érték
        IntervalEnd: 
          type: object
          description: Dátum szűrés záró érték
      description: A szűrés feltétele.
    OperationResponse:
      type: object
      properties:
        ResponseCode:
          type: string
          description: Hibás válasz esetén a hiba kódja, egyébként üres.
        Message:
          type: string
          description: Üzenet magyarul.
        MessageEN:
          type: string
          description: Üzenet angolul.
        Details:
          type: string
          description: Hiba esetén a hiba okának részletes leírása, egyébként üres.
        content:
          type: object
          description: Ha a válasznak tartalmaznia kell valamilyen tartalmat, akkor ebben van, egyébként üres.
        StatusCode:
          type: integer
          description: Kérés eredménye HTTP válaszkód szerint
    ErrorCodes:
      type: string
      enum:
         - E001: Token nem található, vagy a Tokennel nincs aktív session.
         - E002: A kérés feldolgozása sikertelen.
         - E003: A kérés feldolgozása közben kivétel keletkezett.
        